### ISSUE TITLE
InventoryCloseEvent NPE on closing chests in vanish

### ISSUE THREAD

**Issue by kekke3r** [arboriginal/TidyingChest#1]
Version of Paper: Paper 1.14.4 build 221
Version of plugin: 0.6
Plugin that manages vanish mode: CMI 8.6.15.2

Everytime a player in vanish opens and then closes a chest (any type of normal chest) in silent mode the plugin throws a NPE in console

Error: https://pastebin.com/YjJe17nK

**Comment by kekke3r** [comment]
The dev build 0.7a solves the Issue! No NPE error on console after several attempts, great! Thanks a lot for the support

**Comment by kekke3r** [comment]
I will downgrade although to 0.6 because after breaking and unlinking a chest the whole server crashed

**Comment by kekke3r** [comment]
no, was testing the plugin without vanish on, it keeps crashing the server on version 0.6 and 0.7a, maybe some interaction with other plugins broke the whole thing, tried also to delete  the .db file and restarted the server but as soon as i load the chunk in which the chests were broken the server crashes
Here is the paste of the first crash https://pastebin.com/AHmAtSyB

**Comment by kekke3r** [comment]
I also discovered that opening every type of gui provided by cmi causes the server to throw errors like the paste above and crashing it. So it's confirmed that it's the CMI - Tidyng Chest interaction that causes this issue. Will try to report it to cmi developer and at this point i think we can close this issue, btw thanks for your help, time and efforts, I really appreciate it.

**Comment by arboriginal** [comment]
Can't say, never had this problem with tons of tests I did during development and now... Try without other plugins, then add them one by one / by group to find which one could interfere with TidyingChest. Unfortunately, if I can't reproduce, I can't fix.

But it's strange your server crash when you load a chunk because TidyingChest does nothing on chunk loads... It only react to those events:
- BlockBreakEvent => Del if chest / sign is handle by the plugin (ie in DB)
- InventoryCloseEvent => Transfer if chest is handle by the plugin (ie in DB) and ROOT
- InventoryMoveItemEvent => (when hopper put items in chest) Transfer if (1) and chest is ROOT
- PlayerInteractEvent => interact on sign (to create a TARGET chest)
- SignChangeEvent => create ROOT chest / init TARGET creation

Moreover, You can see in your log « [TidyingChest] All chests in your database has been verified (total: 0 - 0 removed). » so TidyingChest have no chests to work with.

Try to disable it, explore the chunk and verify it's not corrupt or something like that...

**Edit:** After reading your last message, I've tested with some GUI plugin and have no errors...

When you'll report this to CMI dev, give him a link to my plugin source code, and let me know if he gives you useful informations to prevent other plugins to have errors with TidyingChest.
