### ISSUE TITLE
Server freezes on startup, papermc 1.14.4 r221, Tidyingchest 0.7

### ISSUE THREAD

**Issue by hashashin** [arboriginal/TidyingChest#2]
Freeze dump: https://pastebin.com/wgPBfGCU
Plugin list: https://pastebin.com/NT1k0Tsi
Server just freezes when startup ends or when a player connects and opens a chest. I tried disabling the obvious plugins that I guess can interfer: AutomaticInventory, SilkChests, OpenInv and VehicleStorage, with no luck.
Using default settings in your plugin.

Thanks.

**Comment by arboriginal** [comment]
Can't reproduce, you have to try without your other plugins to identify which one interferes. Other plugins are named in the log errors: CSCoreLibPlugin, bentobox, plotsquared for example (I maybe miss some) so I'll start by trying without them. I can't be sure they are responsible for it, or if it's result but as I'm not using them and never have this problem with / without my other plugins...

This is also very surprising if you use default config because this use a SQLITE database (a file) so it should be lag-free... Are you sure to also use default for database settings? FYI, at startup a synchronous connection is done to the database and orphan chests are checked (**this is clearly written in the logs**) + when player CLOSE (not open) a chest the first time is when his datas are retrieved from database. **Those 2 things are indicated in the doc (see your config.yml header)**.

BUT... in game (so, except ones at startup), database queries are done **asynchronous**, so your server should not freeze! I've tested with a voluntary very very slow MySQL server during development + next days + just now ; I've also re-tested just now with a modification in the code to **simulate a 15 sec lag for database** and as attendee, the response from DB is slow to come but the server doesn't freeze at all.

So, as I always said, if I can't reproduce, I can't fix (I did my tests on same version of paper). I let you make your tests without other plugins to tell me which one TidyingChest doesn't work with, then if I can reproduce myself I'll try to fix, otherwise I won't.

**Comment by hashashin** [comment]
I did some more tests and I'm more confused now, server with no plugins but yours, world it's already generated and has some normal chests. Startup as normal but after some interactions with the chests it freezes (open, close, move around objects).
Some more info about the server: debian buster, OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10), java startup options: "-server -Xms4096M -Xmx4096M -Xgc:concurrentScavenge -Xgc:dnssExpectedTimeRatioMaximum=3 -Xgc:scvNoAdaptiveTenure -Xdisableexplicitgc -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+UseCompressedOops -XX:+UseLargePages -XX:+UseStringCache -XX:+UseCompressedStrings -XX:+OptimizeStringConcat". Nothing special in the server config files, but I can provide them if you want.

**Comment by hashashin** [comment]
Ok it's not freezing now, after switching from sqlite to mysql... 15min up now with all the original plugins and tidy.

**Comment by hashashin** [comment]
Nervermind, I tried to create a root and a destination chest, the root one I can see the entry in the table, but after creating the sign for the destination it freezes again :(

**Comment by arboriginal** [comment]
Strange! I would reply you the problem could be because you're using JRE 11 (the plugin is compiled and recommenced for java 8), not sure at all but it can be a lead... But if it works well with MySQL and not SQLITE it's surprising!

Did you used in the past version 0.5 (in which queries was run synchronous), and if yes did you have no problems with?

Maybe if you are a bit familiar with Java you can try compiling your own version, adding some debug informations in it, for example by adding things like `System.out.println("write sth");`... Maybe the fact to be compiled with you're version of java will change something.

**Edit:** Hum... And "after creating the sign for destination", do you talk about a complete target sign or while it waits for you hit with an item? FYI, the entry in DB in only set after the item is set.

TBH, I've actually no clue what's happening to you, but I'll try to make tests with another JRE. Not today because I'll be out but if I'm not tired, I'll tried during the night.

**Comment by hashashin** [comment]
I'll try with adoptopenjdk-8 without plugins (no normal openjdk 8 on buster afaik) and if that works recompile it with adoptopenjdk-11.

**Comment by arboriginal** [comment]
I did a quick test with JRE 12 and no problem at all...

``
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

java version "12" 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)
``

But also: When datas have been retrieved from DB once for a player, there are cached in code.

If the freeze is while it's waiting it's... strange again! It simply create a BukkitRunnable (which will be called later to, if not canceled, break the sign) + temporary store this task in a HashMap (to be able to cancel it).

**Comment by hashashin** [comment]
After more tests the far I can go its with adoptopenjdk-8, all seems to be working, can create chests, tranfers works, but after a while it freezes again. Recompile did not help. 
Dunno whats going on here so I'm gonna desist, I dont want to make you loss more time in this, thanks anyway :)

PS: If I get bored maybe I'll try some more things, if I find anything I'll reopen the issue.

**Comment by arboriginal** [comment]
Ok, I'll try to check by my side during the night and let you know if I find something useful.
BTW, you didn't reply about version 0.5. You can maybe use this one until a solution is found.

**Comment by arboriginal** [comment]
Sorry, I was back too late yesterday and directly sleep... I'll try to go on tests in the next days.

**Comment by arboriginal** [comment]
Tested right now with OpenJDK without any problems...

```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)
```
Your java arguments are: (I re-list them here for me)
```
-server
-Xms4096M
-Xmx4096M
-Xgc:concurrentScavenge
-Xgc:dnssExpectedTimeRatioMaximum=3
-Xgc:scvNoAdaptiveTenure
-Xdisableexplicitgc
-XX:+AlwaysPreTouch
-XX:+ParallelRefProcEnabled
-XX:+UseCompressedOops
-XX:+UseLargePages
-XX:+UseStringCache
-XX:+UseCompressedStrings
-XX:+OptimizeStringConcat
```

I will try to play with them, but that's the last thing I could test...
After that I give up if I didn't successfully reproduce the issue.

**Comment by arboriginal** [comment]
OK, so... I've tried to run the server with AdoptOpenJDK 1.8 and all your options, but a few ones are not recognized on my computer (Mac OS 64bits), so I remove them and all works fine. So, I suppose the problem is with those options I couldn't try:

```
# Those errors stop the command, so I removed the option then restart for each of them
Unrecognized option: -Xgc:concurrentScavenge
Unrecognized option: -Xgc:dnssExpectedTimeRatioMaximum=3
Unrecognized option: -Xgc:scvNoAdaptiveTenure
Unrecognized option: -Xdisableexplicitgc
Unrecognized VM option 'UseCompressedStrings'
# Following lines are only warning as the server starts anyway
OpenJDK 64-Bit Server VM warning: ignoring option UseStringCache; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: -XX:+UseLargePages is disabled in this release.
```

I didn't search deeper but for the first one:
https://github.com/eclipse/openj9/issues/3451
(even if I'm not on Windows but on Mac)

You should have a look at those specific options, maybe try without them if you can, and probably remove "UseStringCache" as it's apparently no more used.

**Comment by arboriginal** [comment]
I've downloaded AdoptOpenJDK 1.11...

```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)
```

and same result, except a few options not recognized, no errors, no freeze.

```
# Those errors stop the command, so I removed the option then restart for each of them
Unrecognized option: -Xgc:concurrentScavenge
Unrecognized option: -Xgc:dnssExpectedTimeRatioMaximum=3
Unrecognized option: -Xgc:scvNoAdaptiveTenure
Unrecognized option: -Xdisableexplicitgc
Unrecognized VM option 'UseStringCache'
Unrecognized VM option 'UseCompressedStrings'
# Following line is only warning as the server starts anyway
OpenJDK 64-Bit Server VM warning: -XX:+UseLargePages not supported in this VM
```

**Comment by hashashin** [comment]
Odd, it's that the one with the openj9 vm? because by default it's downloads the hotspot one. I guess those options are for the openj9 one only.
My "java -version":
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191017_442 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)

I'm in 1.8 for now as it's seems to fix another plugin... same launch options as in 11.

**Comment by llronaldoll** [comment]
I have the same problem, how did you fix it? use windows 10
