### ISSUE TITLE
Plugin deletes chests from db if loaded before Multiverse-Core.

### ISSUE THREAD

**Issue by hashashin** [arboriginal/TidyingChest#3]
Step to reproduce: 
Create at least another world with multiverse, ex: "/mv create newworld", then "/mvtp newworld" to go there.
Create some chests in the new world, restart the server.
Tidychest now loads before multiverse-core and can't find the "newworld" as it's not loaded, then it removes the chests in that world.

Similar to Derpy00001/MoreBosses#4.
I used the same workaround, add Multiverse-Core to softdepends, so bukkit load the plugin after and it can find the world and chests.

EDIT: forgot to mention this is in 0.5 but should be the same in 0.7.
EDIT2: not native english I messup with the after and before, ouch, should be good now.

**Comment by arboriginal** [comment]
Thanks reporting it, as I've never used multiverse, I didn't see this...
(don't worry, I'm not native english too and I understood what you said)

I will check how to fix it in another way because this method of putting mv as a soft depend will not fix it for other plugins like it (I don't know, for example "Multiverse-core-reloaded" or "Multiverse-core-custom" fictional plugins will not works until I also add them into soft depend...)

For now, the temporary solution is to disable orphan check at startup:
```
cleanOrphans:
  enabled: false
```

I'll make tests  and fix it in a next version!

**Comment by arboriginal** [comment]
@hashashin, as I said I've preferred not to put MV as a soft dependency, but add a configurable list of plugins to wait for they're loaded before to execute the orphans check. So that ref to MV is not hardcoded and let server admins to use my plugin with it and also with alternatives. I've also added an option not to directly delete found orphans from database and only warn.

Thanks again for the report, I've mentioned you in the plugin update:
https://www.spigotmc.org/resources/tidyingchest.64206/update?update=303119
